service: verify-code
frameworkVersion: '3'

custom:
  tableName: 'verify-table-${sls:stage}'

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  
provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: nodejs14.x
  memorySize: 256 # mb
  timeout: 10 # seconds
  logRetentionInDays: 90
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - '*'
            - Fn::GetAtt: [ VerifyTable, Arn ]

        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - '*'
  environment:
    VERIFY_TABLE: ${self:custom.tableName}
  apiGateway:
    apiKeySourceType: HEADER
    apiKeys:
      - ${self:provider.stage}-VERIFY-API-KEY
    usagePlan:
      quota:
        limit: 100
        period: DAY
      throttle:
        rateLimit: 5
        burstLimit: 20

functions:
  smsSend:
    handler: ./src/sms/services/sms-send.sender
    events:
      - http:
          path: sms/
          method: post
          private: true
  smsGet:
    handler: ./src/sms/services/sms-get.get
    events:
      - http:
          path: sms/{code}
          method: get
          private: true

package:
  individually: true

resources:
  Resources:
    VerifyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: code
            AttributeType: S
        KeySchema:
          - AttributeName: code
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
        TimeToLiveSpecification:
          AttributeName: expires_at
          Enabled: true
